version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16  
    working_directory: ~/project
    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: npm install 
      - run:
          name: Run tests
          command: npm test  
      - run:
          name: SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey="Rushil777_APDS-PaymentsPortal" \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
