version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:16  # Use a more recent version of Node.js
    steps:
      - checkout  # Check out the code
      - run:
          name: Change directory to Backend
          command: cd Backend  # Navigate to the Backend folder
      - run:
          name: Install npm dependencies
          command: npm install --save  # Install dependencies in the Backend folder
      - run:
          name: SonarQube Analysis
          command: |
            # Run SonarQube analysis with locally installed scanner in Backend folder
            npx sonarqube-scanner \
              -Dsonar.projectKey=Rushil777_APDS-PaymentsPortal \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test
